class cashieringSystem:
     def __init__(self, a=0, r=0, recieve=0, change=0, temp=0):
        print("\n\n*****Welcome to simple Cashiering System*****\n")
        self.a=a
        self.r=r
        self.recieve=recieve
        self.temp=temp
     def foods(self):
        print("*****Mullu's Restourtant Menu*****")
        print("1. Burger-----&gt; 70", "\n2. Pizza-------&gt; 150", "\n3. Veg Roll-------&gt; 50", "\n4. Coffee------&gt; 40", "\n5. Cash Out", "\n6. Exit")
        while(1):
            c = int(input("Choose :\n"))
            if(c==1):
               d=int(input("Enter the quantity : \n"))
               self.r=self.r+30*d
            elif(c==2):
               d=int(input("Enter the quantity :\n"))
               self.r=self.r+35*d
            elif(c==3):
               d=int(input("Enter the quantity :\n"))
               self.r=self.r+50*d
            elif(c==4):
               d=int(input("Enter the quantity :\n"))
               self.r=self.r+40*d
            elif(c==5):
                 quit()
            else:
                 print("Invalid Option")
            print("Total :", self.r)
            if(self.r != 0):
               recieve =int(input("Input Money Received :\n"))
               print("Change : ",recieve-self.r)
               print("*****Thank You Come Again!!!*****")
               quit()
def main():
   a = cashieringSystem()
   while(1):
    a.foods()
main()
